spring:
  application:
    name: social-notifications-service
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

app:
  producer: social-notifications-service
  kafka:
    topics:
      notification-events: notification-events
      chat-events: chat-events
      mail-events: mail-events
      moderation-events: moderation-events
  outbox:
    poll-interval-ms: 3000
    max-attempts: 5
